API- serve static photo and set profile photo
iSchoolProjects/backend-project-1-simple-blog-platform pull request #2
Opened 2021-09-07 10:57 UTC by koovaaaa

2021-09-07 11:01 UTC, DejanMaksimovic commented on src/user/user.controller.ts
> +    @Param('imgID') imgID: string,
Please check naming convention on this parameter.

2021-09-07 11:06 UTC, DejanMaksimovic commented on src/user/user.service.ts
> +  async seeUploadedPhoto(img_id: string, user: User): Promise<string> {
Here also img_id is not following naming convention that is being used in whole project. So here we should use camelCase convention.

2021-09-07 11:13 UTC, zlayabekrija requested changes
Great work, great improvements, minor fixes are needed. 
Please address them and continue good work :+1:

2021-09-07 11:13 UTC, zlayabekrija commented on src/user/user.service.ts
> +      return `${process.env.APP_HOST}:${process.env.APP_PORT}${PathUploadEnum.SERVE_USER_PHOTO}${user.id}/${user_photo.image}`;
API consumer should know the url (APP_HOST) and port number(APP_PORT), hence those two params are unnecessary.

2021-09-07 11:13 UTC, zlayabekrija commented on src/user/user.service.ts
> +  async findPhoto(id: string, user: User) {
What does this method return?
Do we need whole User object if we are using only userId. One of the solid principles is that we shouldn't know who is giving us params.

Since the UserPhoto is independent entity, it should be placed in the user photo repository.

2021-09-08 13:09 UTC, DejanMaksimovic approved these changes

2021-09-08 13:13 UTC, zlayabekrija approved these changes

2021-09-08 13:15 UTC, merged